### PR TITLE
Update to latest version of React Router. 

### PR DESCRIPTION
**Pull request by erikshestopal**
I went ahead and pulled in the latest version of react-router.js and react-router.min.js.
Suggestions welcome.

### CODE REVIEW

**Comment by troter** [comment]
:+1:

**Comment by erikshestopal** [comment]
@troter Anything else that should be updated?

**Comment by erikshestopal** [comment]
@rainchen Fixed. Take another once-over, please.

**Comment by rainchen** [comment]
@thisiserik maybe need to update react_router_ujs.js, checkout this change
https://github.com/jimknight/react-router-rails/commit/909df14670ce189975f2057c4dd4d5199bfc3d96

**Pull request merged**
